### ISSUE TITLE
It's generating an error.

### ISSUE THREAD

**Issue by Leozgu** [xvorost/CS-2-Glow#2]
I'm trying to generate an executable program using Visual Studio, but it fails!

**Comment by xvorost** [comment]
Go to the project settings and paste your path to the included DirectX files

**Comment by xvorost** [comment]
> I'm trying to generate an executable program using Visual Studio, but it fails!

did you figure out the problem?

**Comment by Leozgu** [comment]
Thank you very much for your reply, I have fixed all the errors that I can troubleshoot, I only have these four reported errors left that I don't know how to fix, please help me.

![2023-11-21 175743](https://github.com/xvorost/CS-2-Glow/assets/80804904/f0505469-6c9b-4a8b-85ce-b8ab901afb4a)
