### ISSUE TITLE
Bannable or not?

### ISSUE THREAD

**Issue by Synx400** [xvorost/CS-2-Glow#4]
Does this inject any things on game files?
or its Bannable or Antban?

**Comment by Loshara1337** [comment]
Yes, this cheat writes memory so it is obvious that playing with it will not cause anything good, especially it is available to everyone which increases the chance of being banned.

**Comment by xvorost** [comment]
> Does this inject any things on game files? or its Bannable or Antban?

There have been no complaints about blocking yet
